name: Build Sonic 1 and 2 for PS Vita
on:
  push:
    branches:
      - master
      - main
      - psvita

jobs:
  sonic1-psvita:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add --no-cache make cmake
      - name: Build Sonic 1
        run: |
          cd Sonic1.Vita
          cmake .
          make
      - name: Upload VPK
        uses: actions/upload-artifact@v2
        with:
          name: Sonic1-vita
          path: Sonic1.Vita/Sonic1.vpk
          if-no-files-found: error
  sonic2-psvita:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add --no-cache make cmake
      - name: Build Sonic 2
        run: |
          cd Sonic2.Vita
          cmake .
          make
      - name: Upload VPK
        uses: actions/upload-artifact@v2
        with:
          name: sonic2-vita
          path: Sonic2.Vita/Sonic2.vpk
          if-no-files-found: error
